<a href="https://colab.research.google.com/github/Krupique/Tensorflow2/blob/master/Introdu%C3%A7%C3%A3o_tensorflow2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow 1.X

###Instalando o TensorFlow 1.X

In [0]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 82kB/s 
     |████████████████████████████████| 368kB 41.1MB/s 
     |████████████████████████████████| 3.2MB 33.8MB/s 
ERROR: tensorflow 1.14.0 has requirement tensorboard<1.15.0,>=1.14.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 1.14.0 has requirement tensorflow-estimator<1.15.0rc0,>=1.14.0rc0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.13.1'

###Constantes

####Definindo uma constante

In [0]:
#Definindo uma constante no Tensorflow
tensor = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [0]:
#Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor.eval() #Exemplo de erro

####Acessando os valores de uma constante

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [0]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

###Variáveis

####Definindo uma variável

In [0]:
#Definindo uma variável no Tensorflow
variable = tf.Variable([[30, 20],[10, 45]])

In [0]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [0]:
#Se uma sessão não for inicializada, não podemos acessar os valores das variáveis
variable.eval() #Exemplo de erro

####Acessando os valores de uma variável

In [0]:
#Inicializando uma sessão
session = tf.Session()

In [0]:
#Inicializando TODAS as variáveis de uma sessão
session.run(tf.global_variables_initializer())

In [0]:
#Executando o método eval no ambiente com a sessão inicializada para conseguir buscar os valores
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#TensorFlow 2.0

###Instalando o TensorFlow 2.0

In [0]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 85kB/s 
     |████████████████████████████████| 419kB 41.5MB/s 
     |████████████████████████████████| 3.0MB 32.2MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tf.__version__

'2.0.0-alpha0'

In [0]:
np.__version__

'1.16.5'

###Constantes

####Definindo uma constante

In [0]:
#Definindo uma constante no TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
#Acessando as dimensões de um tensor
tensor_20.shape

TensorShape([2, 2])

In [0]:
tensor_test = tf.constant([[[10, 23],[20, 12]],[[30, 12],[50, 15]],[[60, 80],[70, 45]]])

In [0]:
tensor_test

####Acessando os valores de uma constante

In [0]:
#Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
#Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23, 4],[32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [0]:
tensor_from_numpy

<tf.Tensor: id=27, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

###Variáveis

####Definindo uma variável

In [0]:
tf2_variable = tf.Variable([[1.,2.,3.], [4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

####Acessandos os valores de uma variável

In [0]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

####Acessando um valor específico de uma variável

In [0]:
#Alterar um valor de uma posição específica
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

###Operações com tensores

In [0]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=59, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

####Adição entre um escalar e um tensor

In [0]:
tensor + 2

<tf.Tensor: id=65, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

####Multiplicação entre um escalar e um tensor

In [0]:
tensor * 5

<tf.Tensor: id=73, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

####Usando funções do numpy nos tensores do TensorFlow

In [0]:
#Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [0]:
#Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

####Dot product (Produto escalar) entre dois tensores
Multiplicação de matrizes

In [0]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

###Strings no TensorFlow 2.0

In [0]:
tf_string = tf.constant("Henrique")
tf_string

<tf.Tensor: id=91, shape=(), dtype=string, numpy=b'Henrique'>

####Operações simples com strings

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: id=93, shape=(), dtype=int32, numpy=8>

In [0]:
#Conversão para o formato unicode
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=108, shape=(8,), dtype=int32, numpy=array([ 72, 101, 110, 114, 105, 113, 117, 101], dtype=int32)>

####Armazenamento arrays (vetores) de strings

In [0]:
tf_string_array = tf.constant([["Henrique"],["Krupck"],["Secchi"]])

In [0]:
#Laço para printar todas as strings no arrays
for string in tf_string_array:
  print(string)

tf.Tensor([b'Henrique'], shape=(1,), dtype=string)
tf.Tensor([b'Krupck'], shape=(1,), dtype=string)
tf.Tensor([b'Secchi'], shape=(1,), dtype=string)
